contentdir = 'content'
layoutdir = 'layouts'
publishdir = 'public'
builddrafts = false

baseurl = "https://sidntrivedi.codes"
title = "Siddhant N Trivedi"
theme = "lanyon-hugo"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "sidntrivedi012-github-io-1"

[permalinks]
post = ':year/:month/:day/:title/'
fixed = ':title/'
[markup.goldmark.extensions]
typographer = true
[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
identifier = 'categories'
name = 'Categories'
title = 'Categories section'
url = '/categories/'
weight = -110

[params]
Title = "Siddhant N Trivedi"
Tagline = "Open-Source Contributor & Compilers Enthusiast"
Author = "Siddhant N Trivedi"
DateForm = 'Jan 2 2006'
mainSections = [
    'post',
]


[[params.social]]
name = "Github"
icon = "fab fa-github"
weight = 1
url = "https://github.com/sidntrivedi012/"
[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
weight = 3
url = "https://twitter.com/sidntrivedi012/"
[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/siddhantntrivedi/"
[[params.social]]
name = "Email"
icon = "fas fa-envelope"
weight = 5
url = "mailto:sidntrivedi012@gmail.com"


[languages]
[languages.en]
languagename = "English"


