name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Building the recent changes
      run: |
        brew install hugo
        hugo serve
